// <copyright file="GlobalSuppressions.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("", "CA1014", Justification = "<NikGitStats>", Scope = "module")]
[assembly: SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "<not needed>", Scope = "namespace", Target = "~N:Program")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<can be supressed>", Scope = "member", Target = "~M:Program.Program.ListAllTire(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<can be supressed>", Scope = "member", Target = "~M:Program.Program.Main")]
[assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification = "<need to be supressed>", Scope = "member", Target = "~M:Program.Program.Main")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<can be supressed>", Scope = "member", Target = "~M:Program.Program.GetTireById(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<can be supressed>", Scope = "member", Target = "~M:Program.Program.GetTireById(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<can be supressed>", Scope = "member", Target = "~M:Program.Program.ChangePrice(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<can be supressed>", Scope = "member", Target = "~M:Program.Program.ChangePrice(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<string.>", Scope = "member", Target = "~M:Program.Program.Delete(TireShop.Logic.Logics.LogicAdministration,System.Int32)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<int.parse.>", Scope = "member", Target = "~M:Program.Program.Delete(TireShop.Logic.Logics.LogicAdministration,System.Int32)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<strings.>", Scope = "member", Target = "~M:Program.Program.Create(TireShop.Logic.Logics.LogicAdministration,System.Int32)")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1312:Variable names should begin with lower-case letter", Justification = "<lowercase.>", Scope = "member", Target = "~M:Program.Program.Create(TireShop.Logic.Logics.LogicAdministration,System.Int32)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<strings.>", Scope = "member", Target = "~M:Program.Program.Create(TireShop.Logic.Logics.LogicAdministration,System.Int32)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<string.>", Scope = "member", Target = "~M:Program.Program.ListAllBrands(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<string.>", Scope = "member", Target = "~M:Program.Program.ListAllTireSpecifications(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<string.>", Scope = "member", Target = "~M:Program.Program.GetBrandById(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<string.>", Scope = "member", Target = "~M:Program.Program.GetTireSpecificationById(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<int.parse.>", Scope = "member", Target = "~M:Program.Program.GetTireSpecificationById(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<int.parse.>", Scope = "member", Target = "~M:Program.Program.GetBrandById(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<string.>", Scope = "member", Target = "~M:Program.Program.ChangeBrandCEO(TireShop.Logic.Logics.LogicAdministration)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<int.parse.>", Scope = "member", Target = "~M:Program.Program.ChangeBrandCEO(TireShop.Logic.Logics.LogicAdministration)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<string>", Scope = "member", Target = "~M:Program.Program.ChangeSpeedRating(TireShop.Logic.Logics.LogicAdministration)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<int.parse.>", Scope = "member", Target = "~M:Program.Program.ChangeSpeedRating(TireShop.Logic.Logics.LogicAdministration)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<stringg>", Scope = "member", Target = "~M:Program.Program.GetBrandAVG(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<string>", Scope = "member", Target = "~M:Program.Program.GetBrandAVGASYNC(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<string>", Scope = "member", Target = "~M:Program.Program.MadeOfPLaceSame(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<string>", Scope = "member", Target = "~M:Program.Program.MadeOfPLaceSameAsync(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<string>", Scope = "member", Target = "~M:Program.Program.TireRecommendation(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<int.parse.>", Scope = "member", Target = "~M:Program.Program.TireRecommendation(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "<int.parse.>", Scope = "member", Target = "~M:Program.Program.TireRecommendationASYNC(TireShop.Logic.TireShopLogic)")]
[assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification = "<string>", Scope = "member", Target = "~M:Program.Program.TireRecommendationASYNC(TireShop.Logic.TireShopLogic)")]
